//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/PacketCompletionMessage.msg.
//

#ifndef __PACKETCOMPLETIONMESSAGE_M_H
#define __PACKETCOMPLETIONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class PacketCompletionMessage;
/**
 * Class generated from <tt>messages/PacketCompletionMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * message PacketCompletionMessage
 * {
 *     // Identifier for packet that has been fully processed and that triggered this completion.
 *     int packetId;
 * }
 * </pre>
 */
class PacketCompletionMessage : public ::omnetpp::cMessage
{
  protected:
    int packetId = 0;

  private:
    void copy(const PacketCompletionMessage& other);

  protected:
    bool operator==(const PacketCompletionMessage&) = delete;

  public:
    PacketCompletionMessage(const char *name=nullptr, short kind=0);
    PacketCompletionMessage(const PacketCompletionMessage& other);
    virtual ~PacketCompletionMessage();
    PacketCompletionMessage& operator=(const PacketCompletionMessage& other);
    virtual PacketCompletionMessage *dup() const override {return new PacketCompletionMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketCompletionMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketCompletionMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline PacketCompletionMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<PacketCompletionMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKETCOMPLETIONMESSAGE_M_H

